### ISSUE TITLE
torch-model-archiver --model-name W2V --version 1.0 --serialized-file ./W2V --handler ./Transformer_handler_generalized.py

### ISSUE THREAD

**Issue by luxuantao** [nocoolsandwich/iamQA#1]
torch-model-archiver --model-name W2V --version 1.0 --serialized-file ./W2V --handler ./Transformer_handler_generalized.py

其中serialized-file ./W2V 是不是不太对啊，W2V目录下又来个W2V?

**Comment by nocoolsandwich** [comment]
> torch-model-archiver --model-name W2V --version 1.0 --serialized-file ./W2V --handler ./Transformer_handler_generalized.py
> 
> 其中serialized-file ./W2V 是不是不太对啊，W2V目录下又来个W2V?

是不对,应该是serialized-file ./sgns.merge.word
目标是下载的W2V文件,我readme改一下

**Comment by nocoolsandwich** [comment]
> torch-model-archiver --model-name W2V --version 1.0 --serialized-file ./W2V --handler ./Transformer_handler_generalized.py
> 
> 其中serialized-file ./W2V 是不是不太对啊，W2V目录下又来个W2V?

还有W2V文件夹下的handler,不应该用pickle读取
应该是,刚才更新了
`self.W2V = gensim.models.KeyedVectors.load_word2vec_format(model_pt_path,binary = False)`

**Comment by luxuantao** [comment]
感谢回复，我改过后，运行torchserve --start --ts-config config.properties --model-store model_store --models reader=reader.mar,NER=NER.mar,W2V=W2V.mar的时候有报错


java.lang.InterruptedException
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056)
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2133)
        at java.base/java.util.concurrent.ArrayBlockingQueue.poll(ArrayBlockingQueue.java:432)
        at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:129)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
2020-12-09 10:29:33,738 [WARN ] W-9000-reader_1.0 org.pytorch.serve.wlm.BatchAggregator - Load model failed: reader, error: Worker died.

我的java版本是11

**Comment by nocoolsandwich** [comment]
这个错误好像我这边运行也遇到过,不确定是什么问题,如果服务没问题可以不管。看起来是reader有问题，你可以试试单独测试reader。
`torchserve --start --ts-config config.properties --model-store model_store --models reader=reader.mar`
用request请求看结果
`import requests 
question = '美国特勤局特工通常佩戴什么装备?'.encode('utf-8')  
requests.post('http://127.0.0.1:8080/predictions/my_tc',data=question).text`

**Comment by luxuantao** [comment]
我试了下 没有响应
import requests
question = '美国特勤局特工通常佩戴什么装备?'.encode('utf-8')
print(requests.post('http://127.0.0.1:8080/predictions/reader',data=question).text)

**Comment by luxuantao** [comment]
应该就是reader的问题，NER我也试了下，是好的

**Comment by nocoolsandwich** [comment]
你好，我这边明天用新环境测试一下再给你反馈

**Comment by nocoolsandwich** [comment]
> 应该就是reader的问题，NER我也试了下，是好的

你好，我这边明天用新环境测试一下再给你反馈

**Comment by nocoolsandwich** [comment]
> 感谢回复，我改过后，运行torchserve --start --ts-config config.properties --model-store model_store --models reader=reader.mar,NER=NER.mar,W2V=W2V.mar的时候有报错
> 
> java.lang.InterruptedException
> at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056)
> at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2133)
> at java.base/java.util.concurrent.ArrayBlockingQueue.poll(ArrayBlockingQueue.java:432)
> at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:129)
> at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> at java.base/java.lang.Thread.run(Thread.java:834)
> 2020-12-09 10:29:33,738 [WARN ] W-9000-reader_1.0 org.pytorch.serve.wlm.BatchAggregator - Load model failed: reader, error: Worker died.
> 
> 我的java版本是11

发现问题了解决办法是把reader的
`self.device = torch.device("cuda:" + str(properties.get("gpu_id")) if torch.cuda.is_available() else "cpu")`
更改成
`self.device = torch.device("cuda:0") if torch.cuda.is_available() else "cpu")`
因为配置文件没有写gpu_id,所以properties.get("gpu_id")为None了,更改后需要重新用torch-model-archiver打包一下

**Comment by nocoolsandwich** [comment]
> 感谢回复，我改过后，运行torchserve --start --ts-config config.properties --model-store model_store --models reader=reader.mar,NER=NER.mar,W2V=W2V.mar的时候有报错
> 
> java.lang.InterruptedException
> at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056)
> at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2133)
> at java.base/java.util.concurrent.ArrayBlockingQueue.poll(ArrayBlockingQueue.java:432)
> at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:129)
> at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> at java.base/java.lang.Thread.run(Thread.java:834)
> 2020-12-09 10:29:33,738 [WARN ] W-9000-reader_1.0 org.pytorch.serve.wlm.BatchAggregator - Load model failed: reader, error: Worker died.
> 
> 我的java版本是11

是因为device没监测到,修改代码后没问题了
